version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/run.py
      - FLASK_RUN_HOST=0.0.0.0
      - MYSQL_CONNECTION_STRING=mysql://teste:teste@db/teste_db
    command: >
      bash -c "pip install -r requirements.txt && flask run --host=0.0.0.0"

    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: testdb
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
    ports:
      - "3306:3306"
