version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_DATABASE: Contash
      MYSQL_USER: root
      MYSQL_PASSWORD: shaman
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: Contash
      MYSQL_USER: root
      MYSQL_PASSWORD: shaman
    ports:
      - "3306:3306"
